development:
  adapter: postgresql
  encoding: utf8
  database: fullfill_development
  pool: 5
  username: postgres
  password: farvis12

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: fullfill_test
  pool: 5
  username: postgres
  password: farvis12

production:
  adapter: postgresql
  encoding: utf8
  database: fullfill_production
  pool: 5
  username: postgres
  password: farvis12
